### ISSUE TITLE
What do the columns in the csv files represent?

### ISSUE THREAD

**Issue by motianchi** [chledowski/Robust-Learning-Augmented-Caching-An-Experimental-Study-Datasets#1]
Hello,

There are 2 columns in each .csv file.
Could you please specify what they represent?
Thank you.

**Comment by chledowski** [comment]
Hi!

The first column contains PCs (program counters) which are the load/store instructions to read from/write to memory address. The second one is the cache line address.

https://arxiv.org/pdf/2006.16239.pdf - this paper should be helpful in understanding those in more detail (especially sections 2 & 3).
